# Header
menu:
  Home: /
  Archives: /archives
  Tag: /tags
rss: /atom.xml

# Content
excerpt_link: More...
fancybox: true

# Miscellaneous
google_analytics: UA-67274065-1
favicon: /favicon.png
adv_fetch_url: //manage.zvz.im/api/posts/adv
